import { TransactionTypesConstant } from 'types';

export const NETWORKS = {
  mainnet: 1,
  ropsten: 3,
};

export const TRANSACTION_TYPES: TransactionTypesConstant = {
  NEW_POSITION: 'NEW_POSITION',
  NEW_PAIR: 'NEW_PAIR',
  APPROVE_TOKEN: 'APPROVE_TOKEN',
  TERMINATE_POSITION: 'TERMINATE_POSITION',
  WITHDRAW_POSITION: 'WITHDRAW_POSITION',
  ADD_FUNDS_POSITION: 'ADD_FUNDS_POSITION',
  MODIFY_RATE_POSITION: 'MODIFY_RATE_POSITION',
  NO_OP: 'NO_OP',
};
