name: Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build, lint and test

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: yarn install --pure-lockfile

      - name: Lint
        run: yarn lint
