name: Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Setup and build

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps
        run: yarn install --pure-lockfile

  lint:
    runs-on: ubuntu-latest

    needs: build

    name: Lint

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest

    name: Test

    needs: lint

    strategy:
      matrix:
        node-version: [16.x]


    steps:
      - name: Test
        run: yarn test
