name: Upload to Localazy

on:
  push:
    branches:
      - main
      - staging
  workflow_dispatch:
# Controls when the workflow will run
# on:
#   # Allows you to run this workflow manually from the Actions tab
# We can later enable this if we want them to be upload automatically
# on:
#   push:
#     paths:
#       - 'lang/en.json'

jobs:
  localazy-upload:
    name: Upload strings to Localazy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install deps
        run: yarn install --pure-lockfile

      - name: Extract translations
        run: yarn extract

      - name: Upload translations
        uses: localazy/upload@v1
        with:
          read_key: ${{ secrets.LOCALAZY_READ_KEY }}
          write_key: ${{ secrets.LOCALAZY_WRITE_KEY }}
